### ISSUE TITLE
RefinedStorage API changes.

### ISSUE THREAD

**Issue by Rams59** [gigabit101/QuantumStorage#150]
Everytime i try to get a Modpack loading it chrashes 
[crash-2018-07-20_15.51.42-client.txt](https://github.com/gigabit101/QuantumStorage/files/2214176/crash-2018-07-20_15.51.42-client.txt)
while try to load the Mod

**Comment by gigabit101** [comment]
I will fix this as soon as I get some free time.

**Comment by gigabit101** [comment]
fixed in new build

**Comment by Rams59** [comment]
Works great Thx

**Comment by GamertechAU** [comment]
I've updated to the new build, but still getting crashes from QuantumStorage. Different error though, still to do with RS.
[crash-2018-07-22_12.26.55-client.txt](https://github.com/gigabit101/QuantumStorage/files/2216669/crash-2018-07-22_12.26.55-client.txt)
