### ISSUE TITLE
new CTD with GUI

### ISSUE THREAD

**Issue by metaknight1992** [gigabit101/QuantumStorage#183]
Playing FTB Sky Adventure 1.4.0
Forge 14.23.5.2796
QuantumStorage-1.12-4.6.5
RebornCore-1.12.2-3.13.0.400-universal

this time, opening the QSU gui instantly led to CTD.

Edit: Also happens with the three crates

[https://pastebin.com/T6ZwHLNj](url)

must suck working with core code you don't control.
I hope this isn't too much trouble...

**Comment by modmuss50** [comment]
this should have been fixed update QS and RC

**Comment by BecksIsAlreadyTaken** [comment]
QS and RC updated to the latest version
Still crashes when right-clicking QSU or Quantum tank
